spring.application.name=Noxia

# Puerto del servidor
server.port=8081

# JWT
jwt.secret=NoxiaSecretKeyParaTokenJWT MuyLargaMinimo32Caracteres2024
jwt.expiration=86400000

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Datasource (usar H2 para desarrollo local)
spring.datasource.url=jdbc:h2:mem:noxia
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect